// AUTO-GENERATED by scripts/sync-f1db.ts. Do not edit by hand —
// run `npm run sync:f1db` to refresh. SEASON_STATUS and APP_VERSION are
// preserved across regenerations and may be bumped manually.
export const BUILD_DATA_VERSION = 'F1DB v2026.4.2'
export const BUILD_DATA_SYNC = '2026.05.14'
export const APP_VERSION = 'v0.2.0'
export const SEASON_STATUS = 'F1 2026 — RD 24/24'

// Site-wide totals derived from the synced F1DB snapshot. TOTAL_DRIVERS
// matches the post-filter ranking universe (MIN_STARTS + non-Indy); RACES
// excludes Indy 500 for the same reason. SEASONS is the raw season count.
export const TOTAL_DRIVERS = 466
export const TOTAL_SEASONS = 77
export const TOTAL_RACES = 1160
