const FLAG_EMOJI: Record<string, string> = {
  GB: '🇬🇧',
  DE: '🇩🇪',
  NL: '🇳🇱',
  BR: '🇧🇷',
  AR: '🇦🇷',
  FR: '🇫🇷',
  AT: '🇦🇹',
  ES: '🇪🇸',
  FI: '🇫🇮',
  BE: '🇧🇪',
  IT: '🇮🇹',
  AU: '🇦🇺',
  CA: '🇨🇦',
  US: '🇺🇸',
  MC: '🇲🇨',
  CH: '🇨🇭',
  SE: '🇸🇪',
  MX: '🇲🇽',
  JP: '🇯🇵',
  NZ: '🇳🇿',
  ZA: '🇿🇦',
  PL: '🇵🇱',
  TH: '🇹🇭',
  CO: '🇨🇴',
  VE: '🇻🇪',
  IE: '🇮🇪',
  DK: '🇩🇰',
  PT: '🇵🇹',
  HU: '🇭🇺',
  CN: '🇨🇳',
  RU: '🇷🇺',
  CL: '🇨🇱',
  UY: '🇺🇾',
  MY: '🇲🇾',
  IN: '🇮🇳',
  ID: '🇮🇩',
  CZ: '🇨🇿',
  LI: '🇱🇮',
}

export function flagOf(countryCode: string | null | undefined): string {
  if (!countryCode) return '🏁'
  return FLAG_EMOJI[countryCode.toUpperCase()] ?? '🏁'
}
