-- ============================================================
-- F1-Versus — Seed Constructor Colors
-- ============================================================

INSERT INTO constructors (id, constructor_ref, name, color_hex) VALUES
  (lower(hex(randomblob(16))), 'red_bull',       'Red Bull Racing',      '#3671C6'),
  (lower(hex(randomblob(16))), 'mercedes',       'Mercedes',             '#27F4D2'),
  (lower(hex(randomblob(16))), 'ferrari',        'Ferrari',              '#E8002D'),
  (lower(hex(randomblob(16))), 'mclaren',        'McLaren',              '#FF8000'),
  (lower(hex(randomblob(16))), 'aston_martin',   'Aston Martin',         '#229971'),
  (lower(hex(randomblob(16))), 'alpine',         'Alpine',               '#0093CC'),
  (lower(hex(randomblob(16))), 'williams',       'Williams',             '#64C4FF'),
  (lower(hex(randomblob(16))), 'rb',             'RB',                   '#6692FF'),
  (lower(hex(randomblob(16))), 'kick_sauber',    'Kick Sauber',          '#52E252'),
  (lower(hex(randomblob(16))), 'haas',           'Haas F1 Team',         '#B6BABD'),
  (lower(hex(randomblob(16))), 'alphatauri',     'AlphaTauri',           '#4E7C99'),
  (lower(hex(randomblob(16))), 'alpha_romeo',    'Alfa Romeo',           '#C92D4B'),
  (lower(hex(randomblob(16))), 'sauber',         'Sauber',               '#9B0000'),
  (lower(hex(randomblob(16))), 'racing_point',   'Racing Point',         '#F596C8'),
  (lower(hex(randomblob(16))), 'force_india',    'Force India',          '#FF80C7'),
  (lower(hex(randomblob(16))), 'renault',        'Renault',              '#FFF500'),
  (lower(hex(randomblob(16))), 'lotus_f1',       'Lotus F1',             '#FFB800'),
  (lower(hex(randomblob(16))), 'manor',          'Manor',                '#FF2929'),
  (lower(hex(randomblob(16))), 'marussia',       'Marussia',             '#6E0000'),
  (lower(hex(randomblob(16))), 'hrt',            'HRT',                  '#C0AB00'),
  (lower(hex(randomblob(16))), 'virgin',         'Virgin',               '#CC0000'),
  (lower(hex(randomblob(16))), 'caterham',       'Caterham',             '#006531'),
  (lower(hex(randomblob(16))), 'toro_rosso',     'Toro Rosso',           '#469BFF'),
  (lower(hex(randomblob(16))), 'brawn',          'Brawn GP',             '#B8FF05'),
  (lower(hex(randomblob(16))), 'honda',          'Honda',                '#FFFFFF'),
  (lower(hex(randomblob(16))), 'bmw_sauber',     'BMW Sauber',           '#0F4AFF'),
  (lower(hex(randomblob(16))), 'toyota',         'Toyota',               '#CC0000'),
  (lower(hex(randomblob(16))), 'super_aguri',    'Super Aguri',          '#CC0000'),
  (lower(hex(randomblob(16))), 'spyker',         'Spyker',               '#FF6600'),
  (lower(hex(randomblob(16))), 'midland',        'MF1 Racing',           '#FF0000'),
  (lower(hex(randomblob(16))), 'jordan',         'Jordan',               '#FFD700'),
  (lower(hex(randomblob(16))), 'jaguar',         'Jaguar Racing',        '#006400'),
  (lower(hex(randomblob(16))), 'bar',            'BAR',                  '#C0C0C0'),
  (lower(hex(randomblob(16))), 'minardi',        'Minardi',              '#191919'),
  (lower(hex(randomblob(16))), 'prost',          'Prost',                '#0055A4'),
  (lower(hex(randomblob(16))), 'arrows',         'Arrows',               '#F58020'),
  (lower(hex(randomblob(16))), 'stewart',        'Stewart',              '#FFFFFF'),
  (lower(hex(randomblob(16))), 'tyrrell',        'Tyrrell',              '#003893'),
  (lower(hex(randomblob(16))), 'benetton',       'Benetton',             '#00A0DE'),
  (lower(hex(randomblob(16))), 'ligier',         'Ligier',               '#003893'),
  (lower(hex(randomblob(16))), 'footwork',       'Footwork',             '#F58020'),
  (lower(hex(randomblob(16))), 'brabham',        'Brabham',              '#006633'),
  (lower(hex(randomblob(16))), 'lotus',          'Lotus',                '#FFD700'),
  (lower(hex(randomblob(16))), 'mclaren_historic',  'McLaren (Classic)', '#FF8000'),
  (lower(hex(randomblob(16))), 'williams_historic', 'Williams (Classic)','#003087')
ON CONFLICT (constructor_ref) DO UPDATE SET
  name      = excluded.name,
  color_hex = excluded.color_hex,
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now');
